### ISSUE TITLE
Workflow 

### ISSUE THREAD

**Issue by hack-parthsharma** [PragatiVerma18/Team-Hashtag#7]
Hey Thanks for sharing this wonderful resources Actually the thing is we've got selected as finalist for SIH 2022 and we're confusing on how to create flowchart for our application so can you suggest some good online sites or methods by which you've created your workflow as it seems pretty good.

**Comment by PragatiVerma18** [comment]
Hey Parth, thanks for checking out the repo and congratulations on making it to the SIH 2022 Finals. The workflow diagram was made by our team member @shristisingh29 using Adobe Photoshop and Canva.

You can take reference from online tools like - [Miro](https://miro.com/), [LucidChart](https://www.lucidchart.com/pages/) and [Whimsical](https://whimsical.com/).

I hope you find this helpful.
